### ISSUE TITLE
Potential bug with CPD prediction regularization

### ISSUE THREAD

**Issue by dcolli23** [UM-ARM-Lab/cdcpd#46]
Poking around the code I noticed what might be a bug with the CPD dynamics prediction regularization. Currently, the prediction regularization added to the B matrix (when solving for W) is given by:

```cpp
zeta * (Y_pred.transpose() - Y.transpose());
```

in the CPD inner loop. The problem is that:

1. I don't believe `Y` is updated in the inner loop, meaning that the prediction regularization doesn't change with our updated CPD `TY`.
2. If `Y` *is* updated in the inner loop (due to `TY` being a reference to `Y`,  for example), then this is very confusing syntax and should be changed to reflect the paper more closely.

I propose that the prediction regularization term should instead be:

```cpp
zeta * (Y_pred.transpose() - TY.transpose());
```

**Comment by dcolli23** [comment]
It's certainly possible that I'm incorrect here due to it being some time since I went through the derivation. But it does strike me as odd that the prediction regularization derivative would not change with a `TY` that is closer to the dynamics prediction?

**Comment by lichenTHU** [comment]
Besides, as I want to compare the results of `cpd_output`and `gurobi_output` in Rviz directly, I find the `TY` is output by `TY = cpd(X, Y, TY_pred, Y_emit_prior);`, but the `Y` is already updated by the newest `gurobi_output`  (`deformable_object_configuration_->tracked_.points_`) in upper codes. 

Thus, it also causes that the published message `cdcpd/template` cannot show the the pure CPD result, and it would cover the  `gurobi_output` completely.

**Comment by dcolli23** [comment]
I put the CPD equation through a symbolic matrix derivation calculator and I was, unsurprisingly, wrong about this. The C++ code is correct in using `Y` instead of `TY`.
