### ISSUE TITLE
`cdcpd/template` cannot publish the pure CPD result

### ISSUE THREAD

**Issue by lichenTHU** [UM-ARM-Lab/cdcpd#49]
Besides, as I want to compare the results of `cpd_output` and `gurobi_output` in Rviz directly, I find the `TY` is output by `TY = cpd(X, Y, TY_pred, Y_emit_prior);`, but the `Y` is already updated by the newest `gurobi_output` (`deformable_object_configuration_
->tracked_.points_`) in upper codes.

Thus, it also causes that the published message `cdcpd/template` cannot show the the pure CPD result, and it would cover the `gurobi_output` completely.

This issue is related to the issue #46.

**Comment by lichenTHU** [comment]
When the rope is occluded by obstacles, I just want to compare the shrinking GMM pointset with the not-shrinked gurobi_out in RVIZ directly.&nbsp;
The 'TY' here is correct&nbsp;mathematically, and it always has the information of the occlusion-robust 'Y'.


So I want to get the shrinked true 'Y' of the occluded&nbsp;'X'. But all the messages published are occlusion-robust, such as 'cdcpd/template', which is 'TY'.


In my tests, the message 'cdcpd/template' is almost&nbsp;entirely same as 'cdcpd/output' even under severe occlusion.


I want to get the visualization as same as the paper CDCPD1 in RVIZ as follow, and the two messages are published simultaneously.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UM-ARM-Lab/cdcpd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 凌晨3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [UM-ARM-Lab/cdcpd] `cdcpd/template` cannot publish the pure CPD result (Issue #49)





 
Hi again, can you point out exactly what lines of codes on what branch you're concerned about?
 
From what I can tell, both CPD and Gurobi output are published but they may appear to be the same in RVIZ if the Gurobi post-processing isn't significantly changing the CPD output. This could be the case if CPD isn't causing large stretch in the template, the tracked object isn't interacting with obstacles, or if the tracked object isn't being manipulated by a robotic gripper.

**Comment by lichenTHU** [comment]
![image](https://user-images.githubusercontent.com/73934461/228074746-91ea7215-9699-417d-88e4-14641eb3ecfc.png)

When the rope is occluded by obstacles, I just want to compare the shrinking GMM pointset with the not-shrinked gurobi_out in RVIZ directly.
The 'TY' here is correct mathematically, and it always has the information of the occlusion-robust 'Y'.

So I want to get the shrinked true 'Y' of the occluded 'X'. But all the messages published are occlusion-robust, such as 'cdcpd/template', which is 'TY'.

In my tests, the message 'cdcpd/template' is almost entirely same as 'cdcpd/output' even under severe occlusion.

I want to get the visualization as same as the paper CDCPD1 in RVIZ as follow, and the two messages are published simultaneously.

![image](https://user-images.githubusercontent.com/73934461/228074783-3b25756f-0eee-4fe2-8352-ad3e6a5bff8e.png)

**Comment by lichenTHU** [comment]
I see all your points. What I want to say is, I just want to show the difference between CPD and CDCPD2, but we cannot publish them simultaneously in RViz now.

I would consider your suggestion of using rosbag to the segmented point cloud.

Thank you very much for your work on this project, and I wish you every success in your work.

**Comment by dcolli23** [comment]
Excellent! And it's no problem. Thank you for using CDCPD!

Best out luck!
